# name: CI API Tests
# on:
#   pull_request:
#     types: ['opened']
#     branches: ['erydvan/rest']
# jobs:
#   tests: 
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - uses: actions/setup-node@v3
#     - name: Install dependecies
#       run: npm ci
#     - name: Run API test
#       run: npm run api_tests

name: CI API Tests

on:
  pull_request:
    types: ['opened']
    branches:
      - 'erydvan/rest'

jobs:
  tests: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install dependencies
      run: npm ci
    - name: Run API test
      run: npm run api_tests